version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  backend:
    image: fegor04/it-purple-hack-back
    build:
      target: purple
      context: backend/
    depends_on:
      - "postgres"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "postgres"
      GENERATE_STORAGE: "FALSE"
      GENERATE_RULES: "FALSE"
    restart:
      "always"
  frontend:
    image: fegor04/it-purple-hack-front
    build:
      context: frontend/
    depends_on:
      - "backend"
    ports:
      - "80:80"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
