version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  backend:
    build:
      target: purple
      context: backend/
    depends_on:
      - "postgres"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "postgres"
